In [1]:
import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport

In [20]:
df = pd.read_csv('RealEstateData.csv')
columns = list(df)
df.drop(columns[0],axis = 1, inplace=True)
df

,baths,baths_1qtr,baths_3qtr,baths_full,baths_half,beds,city,garage,list_price,lot_sqft,name,sold_date,sold_price,sqft,stories,sub_type,type,year_built
0,3.0,0,1.0,1.0,1.0,4.0,0,2.0,889000.0,9347.0,0,2021-08-23,940553.0,2018.0,1.0,0,single_family,1960.0
1,3.0,0,0.0,3.0,0.0,3.0,0,2.0,1299000.0,34412.0,0,2021-08-23,1299000.0,3390.0,1.0,0,single_family,1954.0
2,3.0,0,0.0,3.0,0.0,3.0,0,2.0,1325000.0,10568.0,0,2021-08-23,1275500.0,3502.0,2.0,0,single_family,1978.0
3,2.0,0,0.0,2.0,0.0,2.0,0,3.0,749000.0,0.0,0,2021-08-21,750000.0,0.0,1.0,0,single_family,1925.0
4,2.0,0,0.0,1.0,1.0,2.0,0,2.0,399000.0,63423.0,0,2021-08-21,400000.0,937.0,2.0,condo,condos,1963.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,3.0,0,0.0,2.0,1.0,3.0,Anaheim,2.0,750000.0,3036.0,0,2021-07-27,820000.0,2023.0,2.0,0,single_family,1981.0
1996,2.0,0,0.0,2.0,0.0,2.0,Anaheim,2.0,625900.0,0.0,0,2021-07-27,675000.0,1530.0,1.0,condo,condos,1980.0
1997,2.0,0,0.0,2.0,0.0,3.0,Anaheim,2.0,758000.0,6461.0,0,2021-07-27,758000.0,1228.0,1.0,0,single_family,1955.0
1998,3.0,0,0.0,2.0,1.0,4.0,Anaheim,3.0,899000.0,7200.0,0,2021-07-26,905500.0,2089.0,1.0,0,single_family,1968.0
1999,2.0,0,0.0,2.0,0.0,4.0,Anaheim,0.0,0.0,6060.0,0,2021-07-26,700000.0,1240.0,1.0,0,single_family,1957.0

In [21]:
df1 = pd.DataFrame(np.random.rand(100, 5), columns=["a", "b", "c", "d", "e"])

In [22]:
profile = ProfileReport(df1)

TypeError: concat() got an unexpected keyword argument 'join_axes'